version: "3.1"

services:
  db:
    image: postgres:latest
    platform: linux/arm64
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
    volumes:
      - ./tmp/postgresql:/var/lib/postgresql/data
    ports:
      - 54321:5432
